-- Add nl_description and rule_config columns to escalation_rules
-- nl_description: plain-English description generated by AI config builder
-- rule_config: complete structured config from AI (superset of trigger_config + action_config)
-- Run this in the Supabase SQL editor

ALTER TABLE escalation_rules
  ADD COLUMN IF NOT EXISTS nl_description TEXT,
  ADD COLUMN IF NOT EXISTS rule_config JSONB;

-- Backfill rule_config from existing trigger_config + action_config for existing rows
UPDATE escalation_rules
SET rule_config = jsonb_build_object(
  'rule_name', rule_name,
  'description', description,
  'trigger_type', trigger_type,
  'trigger_config', trigger_config,
  'action_type', action_type,
  'action_config', action_config,
  'priority', priority,
  'active', active
)
WHERE rule_config IS NULL;
