// Shared demo fixtures for demoMode across modules.
// Narrative: mid-size telecom CSP that's been using EngageWorx for ~3 months.
// Same cast appears in pipeline, contacts, inbox, and helpdesk so the demo
// feels coherent when the SP admin walks a prospect through the product.

const MINUTE = 60 * 1000;
const HOUR = 60 * MINUTE;
const DAY = 24 * HOUR;

function fmtDate(d) {
  return new Date(d).toISOString().split('T')[0];
}

// ─── 6 Pipeline Leads ────────────────────────────────────────────────────────
export const DEMO_LEADS = [
  {
    id: 'demo-lead-1',
    name: 'Marcus Chen',
    company: 'Summit Telecom',
    email: 'marcus.chen@summittelecom.com',
    phone: '+1 303 555 0142',
    type: 'Direct Business',
    urgency: 'Hot',
    stage: 'opportunity',
    package: 'Pro $499',
    source: 'Referral',
    notes: 'Rocky Mountain regional carrier, 240 business customers. Evaluating for Q2 rollout. Est MRR: $2,499.',
    last_action_at: fmtDate(Date.now() - 3 * DAY),
    last_activity_at: new Date(Date.now() - 3 * DAY).toISOString(),
    next_action: 'Send formal proposal with custom pricing',
    next_action_date: fmtDate(Date.now() + 1 * DAY),
    ai_next_action: 'Send proposal with 15% volume discount. Reference the CP Expo demo success and offer the Enterprise overage rate.',
    estimated_mrr: 2499,
    contact_count: 2,
  },
  {
    id: 'demo-lead-2',
    name: 'Sarah Whitfield',
    company: 'Blue Ridge Communications',
    email: 'swhitfield@blueridgecomms.net',
    phone: '+1 828 555 0198',
    type: 'White-Label / Reseller',
    urgency: 'Hot',
    stage: 'demo_shared',
    package: 'Enterprise',
    source: 'LinkedIn',
    notes: 'CSP serving Western NC. 80+ clients on legacy platform, looking to migrate. Demo went well. Est MRR: $4,999.',
    last_action_at: fmtDate(Date.now() - 2 * DAY),
    last_activity_at: new Date(Date.now() - 2 * DAY).toISOString(),
    next_action: 'Technical kickoff call Thursday 2pm EST',
    next_action_date: fmtDate(Date.now() + 3 * DAY),
    ai_next_action: 'Send migration timeline template and offer the white-label onboarding package.',
    estimated_mrr: 4999,
    contact_count: 2,
  },
  {
    id: 'demo-lead-3',
    name: 'Jennifer Torres',
    company: 'Coastal Media Group',
    email: 'jtorres@coastalmedia.co',
    phone: '+1 904 555 0167',
    type: 'Direct Business',
    urgency: 'Warm',
    stage: 'inquiry',
    package: 'Starter $99',
    source: 'Event',
    notes: 'Small agency in Jacksonville. CP Expo booth lead. Needs SMS + email for client campaigns. Est MRR: $899.',
    last_action_at: fmtDate(Date.now() - 5 * DAY),
    last_activity_at: new Date(Date.now() - 5 * DAY).toISOString(),
    next_action: 'Walkthrough call scheduled for tomorrow 10am EST',
    next_action_date: fmtDate(Date.now() + 1 * DAY),
    estimated_mrr: 899,
    contact_count: 1,
  },
  {
    id: 'demo-lead-4',
    name: 'David Kowalski',
    company: 'Apex Wireless',
    email: 'dkowalski@apexwireless.com',
    phone: '+1 702 555 0134',
    type: 'White-Label / Reseller',
    urgency: 'Warm',
    stage: 'customer',
    package: 'Pro $499',
    source: 'Direct',
    notes: 'Signed ~2 months ago. 45 active sub-tenants generating ~$21k/mo. Strong referral source. Est MRR: $3,499.',
    last_action_at: fmtDate(Date.now() - 7 * DAY),
    last_activity_at: new Date(Date.now() - 7 * DAY).toISOString(),
    next_action: 'Quarterly business review',
    next_action_date: fmtDate(Date.now() + 14 * DAY),
    estimated_mrr: 3499,
    contact_count: 1,
  },
  {
    id: 'demo-lead-5',
    name: 'Priya Anand',
    company: 'NorthStar Solutions',
    email: 'priya@northstarsol.com',
    phone: '+1 612 555 0189',
    type: 'Agency',
    urgency: 'Hot',
    stage: 'demo_shared',
    package: 'Growth $249',
    source: 'Event',
    notes: 'Met at CP Expo. Marketing agency serving SaaS clients. Wants multi-tenant white-label. Est MRR: $1,299.',
    last_action_at: fmtDate(Date.now() - 2 * DAY),
    last_activity_at: new Date(Date.now() - 2 * DAY).toISOString(),
    next_action: 'Schedule technical deep-dive',
    next_action_date: fmtDate(Date.now() + 2 * DAY),
    ai_next_action: 'Propose a 30-day sandbox and offer to white-label the sender name as "NorthStar Reach".',
    estimated_mrr: 1299,
    contact_count: 1,
  },
  {
    id: 'demo-lead-6',
    name: 'Tom Reilly',
    company: 'Pacific Connect',
    email: 'treilly@pacificconnect.io',
    phone: '+1 415 555 0176',
    type: 'Direct Business',
    urgency: 'Warm',
    stage: 'inquiry',
    package: 'Growth $249',
    source: 'Referral',
    notes: 'Apex referral. Fiber ISP in NorCal, 180 business customers. Wants proactive outage alerts via SMS. Est MRR: $1,899.',
    last_action_at: fmtDate(Date.now() - 6 * DAY),
    last_activity_at: new Date(Date.now() - 6 * DAY).toISOString(),
    next_action: 'Send outage-alert case study',
    next_action_date: fmtDate(Date.now() + 1 * DAY),
    estimated_mrr: 1899,
    contact_count: 1,
  },
];

// ─── 8 Contacts (mapped to the companies above) ─────────────────────────────
export const DEMO_CONTACTS = [
  {
    id: 'demo-c-1',
    firstName: 'Marcus', lastName: 'Chen',
    email: 'marcus.chen@summittelecom.com', phone: '+1 303 555 0142',
    company: 'Summit Telecom', status: 'active',
    tags: ['VIP', 'Prospect', 'Enterprise'], channels: ['Email', 'SMS'],
    created: new Date(Date.now() - 45 * DAY),
    lastActive: new Date(Date.now() - 3 * DAY),
    messagesSent: 18, messagesReceived: 12, openRate: 72.4, clickRate: 28.1, ltv: 0,
    city: 'Denver', state: 'CO',
    notes: 'Primary decision maker at Summit. Evaluating full platform; board review in progress.',
    customFields: { industry: 'Telecom', source: 'Referral' },
  },
  {
    id: 'demo-c-2',
    firstName: 'Lisa', lastName: 'Park',
    email: 'lpark@summittelecom.com', phone: '+1 303 555 0148',
    company: 'Summit Telecom', status: 'active',
    tags: ['Prospect'], channels: ['Email'],
    created: new Date(Date.now() - 44 * DAY),
    lastActive: new Date(Date.now() - 4 * DAY),
    messagesSent: 6, messagesReceived: 4, openRate: 65.0, clickRate: 14.2, ltv: 0,
    city: 'Denver', state: 'CO',
    notes: 'Technical lead at Summit. CC on the proposal thread.',
    customFields: { industry: 'Telecom', source: 'Referral' },
  },
  {
    id: 'demo-c-3',
    firstName: 'Sarah', lastName: 'Whitfield',
    email: 'swhitfield@blueridgecomms.net', phone: '+1 828 555 0198',
    company: 'Blue Ridge Communications', status: 'active',
    tags: ['VIP', 'Enterprise', 'Lead'], channels: ['Email', 'WhatsApp'],
    created: new Date(Date.now() - 38 * DAY),
    lastActive: new Date(Date.now() - 2 * DAY),
    messagesSent: 24, messagesReceived: 19, openRate: 81.2, clickRate: 34.6, ltv: 0,
    city: 'Asheville', state: 'NC',
    notes: 'CEO and primary champion. Running the white-label migration evaluation.',
    customFields: { industry: 'Telecom', source: 'LinkedIn' },
  },
  {
    id: 'demo-c-4',
    firstName: 'James', lastName: 'Holloway',
    email: 'jholloway@blueridgecomms.net', phone: '+1 828 555 0201',
    company: 'Blue Ridge Communications', status: 'active',
    tags: ['Prospect'], channels: ['Email'],
    created: new Date(Date.now() - 35 * DAY),
    lastActive: new Date(Date.now() - 5 * DAY),
    messagesSent: 9, messagesReceived: 7, openRate: 58.3, clickRate: 19.0, ltv: 0,
    city: 'Asheville', state: 'NC',
    notes: 'Ops lead at Blue Ridge. Driving technical evaluation.',
    customFields: { industry: 'Telecom', source: 'LinkedIn' },
  },
  {
    id: 'demo-c-5',
    firstName: 'Jennifer', lastName: 'Torres',
    email: 'jtorres@coastalmedia.co', phone: '+1 904 555 0167',
    company: 'Coastal Media Group', status: 'active',
    tags: ['New', 'SMB'], channels: ['Email'],
    created: new Date(Date.now() - 8 * DAY),
    lastActive: new Date(Date.now() - 5 * DAY),
    messagesSent: 3, messagesReceived: 2, openRate: 66.7, clickRate: 0, ltv: 0,
    city: 'Jacksonville', state: 'FL',
    notes: 'Met at CP Expo booth. Warm but early stage.',
    customFields: { industry: 'Marketing', source: 'Event' },
  },
  {
    id: 'demo-c-6',
    firstName: 'David', lastName: 'Kowalski',
    email: 'dkowalski@apexwireless.com', phone: '+1 702 555 0134',
    company: 'Apex Wireless', status: 'active',
    tags: ['VIP', 'Active', 'Enterprise'], channels: ['Email', 'SMS', 'WhatsApp'],
    created: new Date(Date.now() - 75 * DAY),
    lastActive: new Date(Date.now() - 1 * DAY),
    messagesSent: 87, messagesReceived: 64, openRate: 74.8, clickRate: 31.5, ltv: 6998,
    city: 'Las Vegas', state: 'NV',
    notes: 'Existing customer. 45 sub-tenants live. Pro plan — $499/mo base + overages.',
    customFields: { industry: 'Telecom', source: 'Direct' },
  },
  {
    id: 'demo-c-7',
    firstName: 'Priya', lastName: 'Anand',
    email: 'priya@northstarsol.com', phone: '+1 612 555 0189',
    company: 'NorthStar Solutions', status: 'active',
    tags: ['Prospect', 'Lead'], channels: ['Email', 'SMS'],
    created: new Date(Date.now() - 12 * DAY),
    lastActive: new Date(Date.now() - 2 * DAY),
    messagesSent: 7, messagesReceived: 5, openRate: 71.4, clickRate: 22.0, ltv: 0,
    city: 'Minneapolis', state: 'MN',
    notes: 'CP Expo lead. Agency interested in multi-tenant white-label.',
    customFields: { industry: 'Marketing', source: 'Event' },
  },
  {
    id: 'demo-c-8',
    firstName: 'Tom', lastName: 'Reilly',
    email: 'treilly@pacificconnect.io', phone: '+1 415 555 0176',
    company: 'Pacific Connect', status: 'active',
    tags: ['Prospect'], channels: ['Email'],
    created: new Date(Date.now() - 10 * DAY),
    lastActive: new Date(Date.now() - 6 * DAY),
    messagesSent: 4, messagesReceived: 3, openRate: 50.0, clickRate: 12.5, ltv: 0,
    city: 'San Francisco', state: 'CA',
    notes: 'Referral from Apex. Fiber ISP, 180 customers.',
    customFields: { industry: 'Telecom', source: 'Referral' },
  },
];

// ─── 4 Live Inbox Conversations ─────────────────────────────────────────────
const A_SARAH = { id: 'a1', name: 'Sarah M.', avatar: 'SM', status: 'online' };
const A_JAMES = { id: 'a2', name: 'James K.', avatar: 'JK', status: 'online' };
const A_PRIYA = { id: 'a3', name: 'Priya R.', avatar: 'PR', status: 'away' };
const A_BOT   = { id: 'bot', name: 'AI Bot', avatar: '🤖', status: 'online' };

export const DEMO_CONVERSATIONS = [
  // 1. SMS — agent-handled, Apex Wireless (existing customer) usage question
  {
    id: 'demo-conv-1',
    contact: {
      name: 'David Kowalski', phone: '+1 702 555 0134', email: 'dkowalski@apexwireless.com',
      company: 'Apex Wireless', avatar: 'DK', channel: 'sms', tags: ['VIP', 'Returning'],
    },
    channel: 'sms',
    messages: [
      { id: 'm1-1', from: 'contact', text: "Hey, seeing some overages on this month's usage report. Can you double-check?", time: new Date(Date.now() - 45 * MINUTE), agent: null, read: true, delivered: true },
      { id: 'm1-2', from: 'agent', text: 'Hi David! Pulling it up now — one sec.', time: new Date(Date.now() - 43 * MINUTE), agent: A_SARAH, read: true, delivered: true },
      { id: 'm1-3', from: 'agent', text: "You're at 52,180 SMS this cycle vs the 50k plan limit. Overage is 2,180 × $0.025 = $54.50. I'll add a one-time credit since you're close to a tier upgrade.", time: new Date(Date.now() - 41 * MINUTE), agent: A_SARAH, read: true, delivered: true },
      { id: 'm1-4', from: 'contact', text: 'Appreciate it. Should we bump to the next tier?', time: new Date(Date.now() - 12 * MINUTE), agent: null, read: true, delivered: true },
      { id: 'm1-5', from: 'agent', text: "At your volume the Enterprise plan works out cheaper — 100k SMS/mo included and a lower overage rate. Want me to send the upgrade doc?", time: new Date(Date.now() - 10 * MINUTE), agent: A_SARAH, read: true, delivered: true },
      { id: 'm1-6', from: 'contact', text: 'Yes please', time: new Date(Date.now() - 3 * MINUTE), agent: null, read: false, delivered: true },
    ],
    status: 'active',
    assignedTo: A_SARAH,
    unread: 1,
    lastActivity: new Date(Date.now() - 3 * MINUTE),
    isTyping: false,
    priority: 'normal',
  },
  // 2. WhatsApp — AI handled end-to-end, Blue Ridge post-demo follow-up
  {
    id: 'demo-conv-2',
    contact: {
      name: 'Sarah Whitfield', phone: '+1 828 555 0198', email: 'swhitfield@blueridgecomms.net',
      company: 'Blue Ridge Communications', avatar: 'SW', channel: 'whatsapp', tags: ['VIP', 'Sales'],
    },
    channel: 'whatsapp',
    messages: [
      { id: 'm2-1', from: 'contact', text: 'Following up on yesterday\'s demo — can you share the white-label onboarding doc?', time: new Date(Date.now() - 2 * HOUR), agent: null, read: true, delivered: true },
      { id: 'm2-2', from: 'bot', text: "Hi Sarah! 👋 Thanks for the demo yesterday. Sending the white-label onboarding guide now — it walks through tenant provisioning, branding, and DNS setup.", time: new Date(Date.now() - 2 * HOUR + 30 * 1000), agent: A_BOT, read: true, delivered: true },
      { id: 'm2-3', from: 'bot', text: 'Here it is: docs.engwx.com/csp/onboarding. Want me to also book a 30-min technical kickoff with our solutions engineer?', time: new Date(Date.now() - 2 * HOUR + 60 * 1000), agent: A_BOT, read: true, delivered: true },
      { id: 'm2-4', from: 'contact', text: 'Yes please. Thursday at 2pm EST would work for us.', time: new Date(Date.now() - 90 * MINUTE), agent: null, read: true, delivered: true },
      { id: 'm2-5', from: 'bot', text: "Booked! Calendar invite sent to swhitfield@blueridgecomms.net and I've looped in James (SE). Talk Thursday! 🚀", time: new Date(Date.now() - 89 * MINUTE), agent: A_BOT, read: true, delivered: true },
    ],
    status: 'resolved',
    assignedTo: A_BOT,
    unread: 0,
    lastActivity: new Date(Date.now() - 89 * MINUTE),
    isTyping: false,
    priority: 'normal',
  },
  // 3. Email — AI triaged, escalated to sales. Summit Telecom proposal Q&A
  {
    id: 'demo-conv-3',
    contact: {
      name: 'Marcus Chen', phone: '+1 303 555 0142', email: 'marcus.chen@summittelecom.com',
      company: 'Summit Telecom', avatar: 'MC', channel: 'email', tags: ['VIP', 'Sales'],
    },
    channel: 'email',
    messages: [
      { id: 'm3-1', from: 'contact', text: "Subject: Questions on Proposal v2\n\nHi team — thanks for the updated proposal. Our board has a few concerns about contract length and the early termination fee. Can we discuss before we sign?", time: new Date(Date.now() - 6 * HOUR), agent: null, read: true, delivered: true },
      { id: 'm3-2', from: 'bot', text: "Hi Marcus! Thanks for reaching out. Routing this to our sales team — Priya will reply within the hour since Summit is on our priority list.", time: new Date(Date.now() - 6 * HOUR + 45 * 1000), agent: A_BOT, read: true, delivered: true },
      { id: 'm3-3', from: 'agent', text: "Hi Marcus — Priya here. Happy to discuss. We can flex on contract length (12 or 24 mo) and we waive the early termination fee with 60 days notice. I have 3pm EST open today if you'd like to jump on a call.", time: new Date(Date.now() - 5 * HOUR), agent: A_PRIYA, read: true, delivered: true },
      { id: 'm3-4', from: 'contact', text: "3pm works. I'll send the board chair the dial-in. Thanks for the fast turnaround.", time: new Date(Date.now() - 4 * HOUR - 20 * MINUTE), agent: null, read: false, delivered: true },
    ],
    status: 'active',
    assignedTo: A_PRIYA,
    unread: 1,
    lastActivity: new Date(Date.now() - 4 * HOUR - 20 * MINUTE),
    isTyping: false,
    priority: 'high',
  },
  // 4. Voice — voicemail from Coastal Media, AI transcribed, agent followed up
  {
    id: 'demo-conv-4',
    contact: {
      name: 'Jennifer Torres', phone: '+1 904 555 0167', email: 'jtorres@coastalmedia.co',
      company: 'Coastal Media Group', avatar: 'JT', channel: 'voice', tags: ['New', 'Sales'],
    },
    channel: 'voice',
    messages: [
      { id: 'm4-1', from: 'contact', text: "🎙️ Voicemail (0:42)\n\n\"Hi, this is Jennifer Torres from Coastal Media Group in Jacksonville — we met at the CP Expo booth last week. I'm following up on the starter plan we talked about. I'd love a quick walkthrough of how the SMS + email bundle works for our client campaigns. My number is 904-555-0167. Best time is mornings. Thanks!\"", time: new Date(Date.now() - 1 * DAY - 3 * HOUR), agent: null, read: true, delivered: true },
      { id: 'm4-2', from: 'bot', text: "📝 AI transcript summary: Jennifer Torres (Coastal Media Group) left a voicemail about the Starter plan SMS+email bundle. Requesting a walkthrough. Prefers morning callbacks. Lead tagged as 'inquiry' stage. SMS follow-up auto-sent to confirm receipt.", time: new Date(Date.now() - 1 * DAY - 3 * HOUR + 120 * 1000), agent: A_BOT, read: true, delivered: true },
      { id: 'm4-3', from: 'agent', text: 'Called back and scheduled the walkthrough for tomorrow 10am EST. Added her to the CP Expo nurture sequence.', time: new Date(Date.now() - 1 * DAY - 1 * HOUR), agent: A_JAMES, read: true, delivered: true },
    ],
    status: 'resolved',
    assignedTo: A_JAMES,
    unread: 0,
    lastActivity: new Date(Date.now() - 1 * DAY - 1 * HOUR),
    isTyping: false,
    priority: 'normal',
  },
];

// ─── 3 HelpDesk Tickets ─────────────────────────────────────────────────────
export const DEMO_TICKETS = [
  // 1. Open — billing question (Apex Wireless customer)
  {
    id: 'demo-tk-1',
    ticket_number: 'TKT-1042',
    subject: 'Unexpected overage charge on March invoice',
    description: "We were billed $127 for SMS overage this month but I think we should still be within the 50k limit. Can you audit the usage for Apex Wireless?",
    status: 'open',
    priority: 'normal',
    channel: 'email',
    category: 'billing',
    submitter_name: 'David Kowalski',
    submitter_email: 'dkowalski@apexwireless.com',
    submitter_type: 'tenant',
    ai_handled: false,
    escalation_reason: null,
    created_at: new Date(Date.now() - 4 * HOUR).toISOString(),
    updated_at: new Date(Date.now() - 2 * HOUR).toISOString(),
    tenant_name: 'Apex Wireless',
  },
  // 2. AI-resolved — WhatsApp setup (Summit Telecom)
  {
    id: 'demo-tk-2',
    ticket_number: 'TKT-1041',
    subject: 'How do I verify my WhatsApp Business sender?',
    description: 'Starting WhatsApp setup for Summit Telecom. Got Meta Business Manager connected but the sender shows "pending verification". What\'s the next step?',
    status: 'resolved',
    priority: 'low',
    channel: 'portal',
    category: 'technical',
    submitter_name: 'Lisa Park',
    submitter_email: 'lpark@summittelecom.com',
    submitter_type: 'tenant',
    ai_handled: true,
    escalation_reason: null,
    created_at: new Date(Date.now() - 1 * DAY - 2 * HOUR).toISOString(),
    updated_at: new Date(Date.now() - 1 * DAY - 1 * HOUR).toISOString(),
    tenant_name: 'Summit Telecom',
    resolution_note: 'AI answered: verify via Meta Business Manager → WhatsApp Accounts → Business Verification. Shared step-by-step doc. Confirmed resolved in under 10 minutes.',
  },
  // 3. Escalated — TCR compliance rejection (Blue Ridge Communications)
  {
    id: 'demo-tk-3',
    ticket_number: 'TKT-1039',
    subject: 'TCR campaign registration rejected — URGENT',
    description: 'Our 10DLC brand for Blue Ridge Communications was approved, but our "Customer Service" campaign got rejected with reason code T04 (incomplete sample messages). We have 200+ clients waiting to send. Need escalation — this is blocking our CP Expo launch prep.',
    status: 'escalated',
    priority: 'urgent',
    channel: 'email',
    category: 'technical',
    submitter_name: 'Sarah Whitfield',
    submitter_email: 'swhitfield@blueridgecomms.net',
    submitter_type: 'csp',
    ai_handled: false,
    escalation_reason: 'TCR T04 rejection on customer service campaign. 200+ downstream clients blocked. SLA impact — escalated to compliance team.',
    created_at: new Date(Date.now() - 8 * HOUR).toISOString(),
    updated_at: new Date(Date.now() - 1 * HOUR).toISOString(),
    tenant_name: 'Blue Ridge Communications',
  },
];
