// legalContent.js — Legal page content separated to avoid JSX template literal issues

const privacy = [
  { type: 'p', text: 'EngageWorx ("we," "us," or "our") operates the EngageWorx platform (engwx.com and portal.engwx.com). This Privacy Policy explains how we collect, use, store, and protect your personal data. It applies to all users regardless of location, including the United States, United Kingdom, and European Economic Area (EEA).' },
  { type: 'h', text: 'Data Controller' },
  { type: 'p', text: 'For the purposes of UK GDPR and EU GDPR, the data controller is EngageWorx, based in Miami, Florida, USA. You can contact our data protection team at privacy@engwx.com.' },
  { type: 'h', text: 'Information We Collect' },
  { type: 'p', text: 'We collect the following categories of personal data: account information (name, email address, company name, phone number), billing and payment data (processed securely by a PCI DSS Level 1 certified payment processor), platform usage data (features accessed, session duration, device and browser information), communication data (messages sent through the platform on behalf of your business), technical data (IP address, cookies, log files, and analytics identifiers), and marketing preferences (opt-in status for newsletters and product updates).' },
  { type: 'h', text: 'Legal Bases for Processing (UK and EU)' },
  { type: 'p', text: 'Under UK GDPR and EU GDPR, we process personal data on the following legal bases: contractual necessity, legitimate interests, consent (for marketing communications), and legal obligation (to comply with tax, accounting, and telecommunications regulations).' },
  { type: 'h', text: 'How We Use Your Information' },
  { type: 'p', text: 'We use your data to: provide, operate, and maintain the EngageWorx platform, process subscriptions and billing, send transactional notifications, improve platform performance and develop new features, comply with applicable laws including TCPA (US), PECR (UK), ePrivacy Directive (EU), CAN-SPAM (US), and GDPR (UK/EU), respond to support requests, and detect and prevent fraud.' },
  { type: 'h', text: 'Data Sharing and Third Parties' },
  { type: 'p', text: 'We share data only with vetted service providers operating under data processing agreements. These include providers of carrier-grade messaging and voice infrastructure, PCI DSS Level 1 certified payment processing, proprietary cloud database and authentication services, and anonymized analytics. A current list of sub-processors is available on request to privacy@engwx.com. We do not sell your personal data to third parties, and we do not share your personal data with third parties for their own marketing or promotional purposes.' },
  { type: 'h', text: 'SMS Communications' },
  { type: 'p', text: 'If you provide your mobile phone number and opt in to receive SMS messages from EngageWorx, the following terms apply:' },
  { type: 'p', text: 'No sharing for marketing. No mobile information, including phone numbers and SMS opt-in data, will be shared with third parties or affiliates for marketing or promotional purposes. Mobile opt-in data and consent are not shared with any third parties for marketing.' },
  { type: 'p', text: 'Message types. Messages may include account notifications, billing and invoice alerts, security alerts, support ticket updates, scheduled maintenance notices, and platform usage alerts.' },
  { type: 'p', text: 'Message frequency. Message frequency varies based on your account activity and notification preferences.' },
  { type: 'p', text: 'Costs. Message and data rates may apply, charged by your mobile carrier.' },
  { type: 'p', text: 'Opt-out. You may opt out at any time by replying STOP to any message. Reply HELP for help, or contact us at hello@engwx.com or +1 (786) 982-7800.' },
  { type: 'p', text: 'Sub-processors. SMS messages are transmitted via vetted carrier-grade messaging infrastructure providers operating under signed data processing agreements that prohibit secondary use of your data.' },
  { type: 'p', text: 'Records. We retain SMS consent records — including phone number, timestamp, opt-in method, and the disclosure language shown at the time of consent — for audit and compliance purposes.' },
  { type: 'p', text: 'For full SMS Program Terms, see https://www.engwx.com/sms-terms.' },
  { type: 'h', text: 'International Data Transfers' },
  { type: 'p', text: 'If you are located in the UK or EEA, your data may be transferred to the United States. We safeguard these transfers using Standard Contractual Clauses (SCCs), UK International Data Transfer Agreements (IDTAs), and data processing agreements with all sub-processors.' },
  { type: 'h', text: 'Data Retention' },
  { type: 'p', text: 'We retain your personal data for as long as your account is active. After account deletion, we retain data for up to 12 months for legal compliance, billing records for up to 7 years as required by tax laws, and anonymized analytics data indefinitely for service improvement.' },
  { type: 'h', text: 'Your Rights' },
  { type: 'p', text: 'Depending on your location, you have the right to: access your personal data, correct inaccurate data, request deletion, object to or restrict certain processing, receive a copy of your data in a portable format, and withdraw consent at any time. California residents have additional rights under CCPA/CPRA. UK and EU residents may lodge a complaint with their supervisory authority.' },
  { type: 'p', text: 'To exercise any of these rights, contact us at privacy@engwx.com. We will respond within 30 days.' },
  { type: 'h', text: 'Cookies' },
  { type: 'p', text: 'We use essential cookies required for platform functionality, analytics cookies (consent required in UK/EU), and preference cookies. We respect Do Not Track browser signals.' },
  { type: 'h', text: 'Security' },
  { type: 'p', text: 'We implement industry-standard security measures including TLS 1.3 encryption, AES-256 encryption at rest, row-level security, regular security audits, role-based access controls, and incident response procedures with breach notification within 72 hours as required by GDPR.' },
  { type: 'h', text: 'Children\'s Privacy' },
  { type: 'p', text: 'EngageWorx is not directed at individuals under 16 years of age. We do not knowingly collect data from children.' },
  { type: 'h', text: 'Changes to This Policy' },
  { type: 'p', text: 'We may update this Privacy Policy periodically. Material changes will be communicated via email and a prominent notice on our website.' },
  { type: 'h', text: 'Contact Us' },
  { type: 'p', text: 'For privacy inquiries: privacy@engwx.com | +1 (786) 982-7800. If you are in the UK, you may also contact the ICO at ico.org.uk. If you are in the EU, contact your local Data Protection Authority.' },
];

const terms = [
  { type: 'p', text: 'These Terms of Service govern your access to and use of the EngageWorx platform, including all related websites, APIs, and services. By creating an account or using the Service, you agree to these Terms.' },
  { type: 'h', text: '1. Eligibility' },
  { type: 'p', text: 'You must be at least 18 years old to use the Service. By using the Service, you represent that you have the legal authority to bind the entity on whose behalf you are acting.' },
  { type: 'h', text: '2. Account Registration' },
  { type: 'p', text: 'You agree to provide accurate and complete information during registration, maintain the security of your login credentials, notify us immediately of any unauthorized access, and accept responsibility for all activity under your account.' },
  { type: 'h', text: '3. Description of Service' },
  { type: 'p', text: 'EngageWorx provides an AI-powered customer engagement platform including: omnichannel messaging (SMS, RCS, WhatsApp, Email), AI chatbot and automation tools, visual flow builder, campaign management and analytics, contact management, compliance tools for TCR/10DLC registration, and white-label branding for service providers.' },
  { type: 'h', text: '4. Acceptable Use' },
  { type: 'p', text: 'You agree not to: send unsolicited or spam messages, send messages without proper recipient consent, transmit illegal or harmful content, use the Service for fraud or phishing, attempt unauthorized access to other accounts, reverse-engineer the Service, or exceed rate limits.' },
  { type: 'h', text: '5. Messaging Compliance' },
  { type: 'p', text: 'You are solely responsible for ensuring your messaging activities comply with all applicable laws including TCPA, CAN-SPAM, CTIA guidelines, TCR/10DLC requirements (US), PECR, UK GDPR, Ofcom regulations (UK), and ePrivacy Directive, EU GDPR (EU). We may suspend accounts that violate messaging regulations.' },
  { type: 'h', text: 'SMS Program Details' },
  { type: 'p', text: 'Program Name: EngageWorx Account & Service Notifications. Message frequency varies by business and interaction type. Message and data rates may apply. For help, text HELP to any EngageWorx-powered number. To opt out, text STOP to any EngageWorx-powered number. For support, contact support@engwx.com or call +1 (786) 982-7800.' },
  { type: 'h', text: '6. Intellectual Property' },
  { type: 'p', text: 'The Service is owned by EngageWorx and protected by intellectual property laws. Your subscription grants a limited, non-exclusive, non-transferable license to use the Service. You retain ownership of your content and data.' },
  { type: 'h', text: '7. Billing and Payments' },
  { type: 'p', text: 'Subscription fees are billed monthly or annually. All fees are exclusive of taxes unless stated otherwise. You may cancel at any time; cancellation takes effect at the end of the current billing period. EU/UK consumers may have a right to cancel within 14 days under Consumer Contracts Regulations.' },
  { type: 'h', text: '8. Data Protection' },
  { type: 'p', text: 'Our collection and use of personal data is governed by our Privacy Policy. Where we process personal data on your behalf, we do so under a Data Processing Agreement in compliance with UK GDPR and EU GDPR.' },
  { type: 'h', text: '9. Service Availability' },
  { type: 'p', text: 'We target 99.9% platform uptime but do not guarantee uninterrupted service. We are not liable for downtime caused by factors outside our control.' },
  { type: 'h', text: '10. Limitation of Liability' },
  { type: 'p', text: 'To the maximum extent permitted by law: the Service is provided as-is without warranties of any kind, we are not liable for indirect, incidental, special, consequential, or punitive damages, and our total aggregate liability shall not exceed the fees you paid in the 12 months preceding the claim. Nothing in these Terms excludes liability for death or personal injury caused by negligence, fraud, or any liability that cannot be excluded by applicable law.' },
  { type: 'h', text: '11. Indemnification' },
  { type: 'p', text: 'You agree to indemnify and hold EngageWorx harmless from any claims, damages, or expenses arising from your use of the Service, your violation of these Terms, your violation of messaging regulations, or the content of messages sent through your account.' },
  { type: 'h', text: '12. Termination' },
  { type: 'p', text: 'We may suspend or terminate your account if you breach these Terms, your messaging activity violates applicable laws, your payment is overdue by more than 14 days, or your use poses a security risk. Upon termination, you may export your data within 30 days.' },
  { type: 'h', text: '13. Dispute Resolution' },
  { type: 'p', text: 'United States: Disputes shall be resolved through binding arbitration under the AAA in Miami, Florida. United Kingdom: These Terms are governed by the laws of England and Wales. European Union: These Terms are governed by the laws of your member state. EU consumers may use the Online Dispute Resolution platform at ec.europa.eu/odr.' },
  { type: 'h', text: '14. Modifications' },
  { type: 'p', text: 'We may update these Terms at any time. Material changes will be notified by email at least 30 days before they take effect.' },
  { type: 'h', text: 'Contact' },
  { type: 'p', text: 'For questions about these Terms: legal@engwx.com | +1 (786) 982-7800' },
];

const smsconsent = [
  { type: 'h', text: 'How We Collect Consent' },
  { type: 'p', text: 'EngageWorx and its service provider partners collect consent to send SMS messages through the following methods:' },
  { type: 'p', text: 'Web Form Opt-In: When a customer submits a form on a business\'s website powered by EngageWorx, they are presented with a clear SMS consent checkbox. The checkbox is not pre-checked. The customer must actively opt in before any messages are sent.' },
  { type: 'p', text: 'Point of Service: Customers may provide verbal or written consent during in-person interactions, which is recorded by the business in the EngageWorx platform.' },
  { type: 'h', text: 'What Messages You Will Receive' },
  { type: 'p', text: 'Once opted in, you may receive account notifications, billing and invoice alerts, security alerts, support ticket updates, scheduled maintenance notices, platform usage alerts, and other service-related communications.' },
  { type: 'h', text: 'Message Frequency' },
  { type: 'p', text: 'Message frequency varies based on your account activity and notification preferences. You may receive messages as often as daily depending on usage.' },
  { type: 'h', text: 'How to Opt Out' },
  { type: 'p', text: 'You can stop receiving messages at any time by replying STOP, STOPALL, UNSUBSCRIBE, CANCEL, END, QUIT, REVOKE, or OPTOUT. After opting out, you will receive a confirmation message.' },
  { type: 'h', text: 'How to Get Help' },
  { type: 'p', text: 'Reply HELP to any message for assistance. You can also email support@engwx.com or call +1 (786) 982-7800.' },
  { type: 'h', text: 'Costs' },
  { type: 'p', text: 'Message and data rates may apply. Check with your mobile carrier for details.' },
  { type: 'h', text: 'Privacy' },
  { type: 'p', text: 'No mobile information, including phone numbers and SMS opt-in data, will be shared with third parties or affiliates for marketing or promotional purposes. Your information is handled in accordance with our Privacy Policy at https://www.engwx.com/privacy.' },
  { type: 'h', text: 'Contact' },
  { type: 'p', text: 'For questions about SMS consent: support@engwx.com | +1 (786) 982-7800 | www.engwx.com' },
];

const smsterms = [
  { type: 'p', text: 'These SMS Program Terms govern your enrollment in and use of the EngageWorx SMS messaging program. By opting in, you agree to these terms in addition to the EngageWorx Terms of Service and Privacy Policy.' },
  { type: 'h', text: '1. Program Name' },
  { type: 'p', text: 'EngageWorx Account & Service Notifications' },
  { type: 'h', text: '2. Program Description' },
  { type: 'p', text: 'By opting in to the EngageWorx SMS program, you agree to receive recurring text messages from EngageWorx related to your account. Messages may include billing and invoice notifications, security and login alerts, support ticket updates, scheduled maintenance notices, platform usage alerts, and other service-related communications.' },
  { type: 'h', text: '3. How to Opt In' },
  { type: 'p', text: 'You may opt in to receive SMS messages from EngageWorx by submitting your phone number through the consent form at https://www.engwx.com/smsconsent and actively checking the consent checkbox to confirm your agreement. Consent is not a condition of using the EngageWorx platform.' },
  { type: 'h', text: '4. Message Frequency' },
  { type: 'p', text: 'Message frequency varies based on your account activity and the notifications you have enabled. You may receive messages as often as daily depending on usage.' },
  { type: 'h', text: '5. Message and Data Rates' },
  { type: 'p', text: 'Message and data rates may apply. Please consult your mobile carrier for details on your messaging plan. EngageWorx does not charge for SMS messages, but standard carrier rates from your wireless provider will apply.' },
  { type: 'h', text: '6. How to Opt Out' },
  { type: 'p', text: 'You can cancel the SMS service at any time by texting <strong>STOP</strong> to the number from which you received messages. After you send any opt-out keyword, we will send you a confirmation message that you have been unsubscribed. You will no longer receive SMS messages from EngageWorx unless you opt back in. The following keywords will all opt you out: <strong>STOP</strong>, STOPALL, UNSUBSCRIBE, CANCEL, END, QUIT, REVOKE, OPTOUT.' },
  { type: 'h', text: '7. How to Get Help' },
  { type: 'p', text: 'For assistance, reply <strong>HELP</strong> to any message you receive from EngageWorx, and we will respond with support information. You may also contact us directly at support@engwx.com or +1 (786) 982-7800.' },
  { type: 'h', text: '8. Supported Carriers' },
  { type: 'p', text: 'The EngageWorx SMS program is supported on major U.S. carriers including AT&T, Verizon, T-Mobile, US Cellular, and most other major and MVNO carriers. T-Mobile is not liable for delayed or undelivered messages.' },
  { type: 'h', text: '9. Carrier Liability Disclaimer' },
  { type: 'p', text: 'Carriers are not liable for delayed or undelivered messages. Message delivery is subject to effective transmission from your wireless service provider and is outside the control of EngageWorx.' },
  { type: 'h', text: '10. Privacy' },
  { type: 'p', text: 'Your privacy is important to us. No mobile information, including phone numbers and SMS opt-in data, will be shared with third parties or affiliates for marketing or promotional purposes. For details on how we collect, use, and protect your information, please review our Privacy Policy at https://www.engwx.com/privacy.' },
  { type: 'h', text: '11. Changes to These Terms' },
  { type: 'p', text: 'EngageWorx reserves the right to modify or terminate this SMS program at any time. We will notify users of material changes by posting an updated version of these terms on this page.' },
  { type: 'h', text: 'Contact' },
  { type: 'p', text: 'For questions about these SMS Program Terms: support@engwx.com | +1 (786) 982-7800' },
];

const accessibility = [
  { type: 'p', text: 'EngageWorx is committed to ensuring digital accessibility for people of all abilities. We believe everyone should have equal access to our platform and services.' },
  { type: 'h', text: 'Standards' },
  { type: 'p', text: 'We strive to conform to WCAG 2.1 Level AA, Section 508, the ADA (US), the Equality Act 2010 (UK), EN 301 549 (EU), and the European Accessibility Act.' },
  { type: 'h', text: 'Measures We Have Taken' },
  { type: 'p', text: 'Perceivable: sufficient color contrast ratios, text alternatives for non-text content, responsive design, and no content that relies solely on color.' },
  { type: 'p', text: 'Operable: full keyboard navigation, no keyboard traps, visible focus indicators, sufficient interaction time, and skip navigation links.' },
  { type: 'p', text: 'Understandable: clear navigation patterns, descriptive form labels and error messages, consistent component behavior, and programmatically set page language.' },
  { type: 'p', text: 'Robust: compatibility with major screen readers (JAWS, NVDA, VoiceOver, TalkBack), semantic HTML markup, ARIA landmarks, and regular assistive technology testing.' },
  { type: 'h', text: 'Known Limitations' },
  { type: 'p', text: 'Some third-party embedded content may have accessibility gaps. Certain complex data visualizations may not be fully accessible to screen readers. Older PDF documents may not be fully tagged for accessibility. We are actively working to address these limitations.' },
  { type: 'h', text: 'Testing' },
  { type: 'p', text: 'We regularly evaluate accessibility through automated testing tools (axe, Lighthouse, WAVE), manual keyboard navigation testing, screen reader testing, and periodic third-party audits.' },
  { type: 'h', text: 'Feedback' },
  { type: 'p', text: 'We welcome feedback on accessibility. Contact us at accessibility@engwx.com | +1 (786) 982-7800. We aim to acknowledge feedback within 2 business days and provide a resolution within 10 business days.' },
  { type: 'h', text: 'Enforcement' },
  { type: 'p', text: 'US: File a complaint under the ADA at ada.gov. UK: Contact the Equality Advisory Support Service (EASS) at equalityadvisoryservice.com. EU: Contact your national equality body.' },
];

export const legalPages = {
  privacy: { title: 'Privacy Policy', updated: 'May 1, 2026', sections: privacy },
  terms: { title: 'Terms of Service', updated: 'February 26, 2026', sections: terms },
  smsconsent: { title: 'SMS Consent Policy', updated: 'May 1, 2026', sections: smsconsent },
  smsterms: { title: 'SMS Program Terms', updated: 'May 1, 2026', sections: smsterms },
  accessibility: { title: 'Accessibility Statement', updated: 'February 26, 2026', sections: accessibility },
};
